import { NextRequest, NextResponse } from 'next/server';
import { callOpenRouter } from '@/lib/services/backend/openrouter.service';
import fs from 'fs';
import path from 'path';


export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    // Validate required fields
    if (!body.rubrics || typeof body.rubrics !== 'string' || !body.rubrics.trim()) {
      return Response.json(
        { error: 'Rubrics is required and must be a non-empty string' },
        { status: 400 }
      );
    }

    if (!body.context || typeof body.context !== 'string' || !body.context.trim()) {
      return Response.json(
        { error: 'Context is required and must be a non-empty string' },
        { status: 400 }
      );
    }

    // Extract maxMode parameter from URL query (optional, defaults to false)
    const { searchParams } = new URL(request.url);
    const maxMode = searchParams.get('maxMode') === 'true';

    // Read instructions from JSON file
    const sectionInstructionsPath = path.join(process.cwd(), 'data', 'instructions', 'general-prompts.json');
    let instructions = '';
    
    try {
      const fileContent = fs.readFileSync(sectionInstructionsPath, 'utf8');
      const instructionsData = JSON.parse(fileContent);
      instructions = instructionsData['section-general'];
    } catch (error) {
      console.error('Error reading instructions file:', error);
      return Response.json(
        { error: 'Failed to load instructions from data file' },
        { status: 500 }
      );
    }

    const prompt = `
You are a prompt generation assistant. Your task is to create the prompts for several sections of a chapter in an investment memo. 

Analyze the RUBRICS to define the sections that should be created. Then, for each section, follow the INSTRUCTIONS to write those sections as prompts. A section prompt is a prompt that will be used to generate a section of the investment memo. Additional context for the prompt generation is provided in CONTEXT.

Ensure to follow the INSTRUCTIONS.

## CONTEXT:
${body.context}

## RUBRICS:
${body.rubrics}

## INSTRUCTIONS:
${instructions}

## OUTPUT FORMAT:
Format your response as a JSON object with the following fields:
{
  "section_prompts": {
    "section-prompt-1": "Your generated prompt here...",
    "section-prompt-2": "Your generated prompt here...",
    "section-prompt-3": "Your generated prompt here...",
    ...
  }
}
Verify that the OUTPUT FORMAT is correct and that the JSON is properly formatted. Only return the JSON object, nothing else.
`;

    let parsedResponse;

    if (maxMode) {
      // MaxMode: Call 3 different models and merge results
      const models = [
        'anthropic/claude-sonnet-4',
        'openai/gpt-5',
        'google/gemini-2.5-pro'
      ];

      console.log('MaxMode enabled: Calling multiple models...');
      
      // Call all 3 models in parallel with "one fail all fail" approach
      const modelPromises = models.map(model => 
        callOpenRouter(prompt, model, 'json_object')
      );

      const responses = await Promise.all(modelPromises);
      
      // All models must succeed for maxMode to work
      console.log(`All ${responses.length} models succeeded in maxMode`);

      // Create merge prompt
      const mergePrompt = `
You are a response merger. You have received ${responses.length} different AI responses for the same task of generating section prompts for an investment memo.

Your job is to merge these responses into one comprehensive, high-quality result that combines the best aspects of each response. ALL final section prompts MUST continue to follow the template in TEMPLATE.

## RESPONSES TO MERGE:
${responses.map((response, index) => `
### Response ${index + 1}:
${JSON.stringify(response, null, 2)}
`).join('\n')}

## TEMPLATE:
${instructions.match(/<template>\n([\s\S]*?)<\/template>/)?.[1].trim() || 'Template not found'}

## MERGE INSTRUCTIONS:
1. Analyze and define matching sections to merge by comparing Names and Roles. Each response was generated by a different LLM model, but each model was provided with the same rubrics and instructions, sections are likely to match.
2. Prioritize the best-written and most comprehensive prompts.
3. Do NOT expand the content of the prompts, only combine them. Do NOT include new information. Avoid duplicating information.
4. Ensure that the merged prompts are coherent and consistent and that .

## OUTPUT FORMAT:
Return a JSON object with the exact same structure:
{
  "section_prompts": {
    "section-prompt-1": "Your merged prompt here...",
    "section-prompt-2": "Your merged prompt here...",
    ...
  }
}

Verify that the OUTPUT FORMAT is correct and that the JSON is properly formatted. Only return the JSON object, nothing else.`;

      console.log('Merging responses from multiple models...');
      parsedResponse = await callOpenRouter(mergePrompt, 'google/gemini-2.5-pro', 'json_object');
      
    } else {
      // Standard mode: Single model call
      parsedResponse = await callOpenRouter(prompt, 'openai/gpt-5-mini', 'json_object');
    }
    
    try {
      if (
        parsedResponse.section_prompts && 
        typeof parsedResponse.section_prompts === 'object' &&
        Object.keys(parsedResponse.section_prompts).length > 0
      ) {
        return NextResponse.json({
          data: parsedResponse.section_prompts
        });
      } else {
        throw new Error('Malformed response from LLM');
      }
    } catch (parseError) {
      console.error('Failed to parse LLM response:', parseError);
      console.error('Content:', parsedResponse);
      
      // Provide more helpful error message
      let errorMessage = 'Invalid JSON response from LLM';
      if (parseError instanceof SyntaxError) {
        errorMessage = `JSON parsing failed: ${parseError.message}`;
      }
      
      return NextResponse.json({
        error: errorMessage
      }, { status: 500 });
    }
  } catch (error) {
    console.error('Error in section prompt generation:', error);
    return NextResponse.json({
      error: 'Internal server error'
    }, { status: 500 });
  }
}